# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-19 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='program_type',
            field=models.IntegerField(choices=[(0, 'Undergraduate'), (1, 'Graduate')], default=0),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='main.Admission'),
        ),
    ]
