# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-19 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170119_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='additional_detail',
        ),
        migrations.AddField(
            model_name='admission',
            name='admission_type',
            field=models.IntegerField(choices=[(0, 'Freshman'), (1, 'Transfer')], default=0),
        ),
    ]
