# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170119_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(null=True, upload_to='img/logos'),
        ),
    ]
